version: "3"

services:
  app:
    container_name: app
    build: .
    command: yarn dev
    ports:
      - 8000:8000
    volumes:
      - ./src:/usr/app/src # Comentar em produção
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - postgres-network
      - app-network
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@pgadmin.com'
      PGADMIN_DEFAULT_PASSWORD: 'senha'
    ports:
      - '15432:80'
    depends_on:
      - postgres
    networks:
      - postgres-network
    logging:
      driver: none

networks:
  app-network:
    driver: bridge
  postgres-network:
    driver: bridge
